// AmbientSynth -- measured metadata for the built-in presets: a 2-D map position, a few
// perceptual descriptors and tags. Generated by Tools/preset_map.py from renders of every
// preset (never edited by hand: Core/src/PresetMeta.cpp). The browser filters and sorts on
// this, the map draws it, and PresetMap.h blends between neighbours on the map.
#pragma once
#include <cstdint>

namespace ambient {

enum PresetTag : uint32_t {
    TagDark = 1u << 0, TagBright = 1u << 1, TagCalm = 1u << 2, TagMoving = 1u << 3,
    TagTonal = 1u << 4, TagNoisy = 1u << 5, TagWide = 1u << 6, TagBass = 1u << 7,
    TagDense = 1u << 8, TagSparse = 1u << 9, TagKeys = 1u << 10, TagGenerative = 1u << 11,
    TagCosmos = 1u << 12, TagFeedback = 1u << 13, TagSources = 1u << 14, TagJustIntonation = 1u << 15,
    TagSub = 1u << 16, TagStack = 1u << 17, TagAir = 1u << 18,
};
constexpr int kNumPresetTags = 19;

struct PresetMeta {
    float x, y;                 // map position, 0..1
    float bright;               // 0..1 rank of the spectral centroid
    float motion;               // 0..1 rank of the spectral flux
    float width;                // 0..1 rank of stereo width (1 - |correlation|)
    float noisy;                // 0..1 rank of spectral flatness
    float bass;                 // 0..1 rank of the energy below 150 Hz
    float density;              // 0..1 rank of the mean voice count
    int   family;               // index into familyName()
    uint32_t tags;              // PresetTag bits
};

int               numPresetMeta();          // equals numPresets() once generated, 0 for the stub
const PresetMeta& presetMeta(int index);
int               numPresetFamilies();
const char*       presetFamilyName(int family);
const char*       presetTagName(int bit);   // 0 .. kNumPresetTags-1

} // namespace ambient
