// Generated by Tools/preset_map.py -- do not edit. Measured from renders of every preset.
#include "ambient/PresetMeta.h"
#include "ambient/Presets.h"

namespace ambient {

namespace {
const char* const kFamilies[] = {
    "originals",
    "sleep / night",
    "cathedral / glass",
    "deep / sub / dark",
    "breath / flute / voice",
    "exotic scales",
    "shimmer / delay / motion",
    "cosmos / science fiction",
    "playable keys (brain off)",
    "long-form night arcs",
    "storm / cluster / texture",
    "sources (wavetable, FM, feedback)",
    "z-plane / morphing filter",
};
const char* const kTagNames[kNumPresetTags] = {
    "Dark", "Bright", "Calm", "Moving", "Tonal", "Noisy", "Wide", "Bass", "Dense", "Sparse", "Keys", "Generative", "Cosmos", "Feedback", "Sources", "JustIntonation", "Sub", "Stack", "Air"
};
const PresetMeta kMeta[] = {
    { 0.3649f, 0.7445f, 0.456f, 0.422f, 0.293f, 0.483f, 0.592f, 0.102f, 0, 0x8a00u },   // Init
    { 0.3113f, 0.6438f, 0.150f, 0.327f, 0.476f, 0.687f, 0.905f, 0.211f, 0, 0x18a81u },   // Sleep Concert
    { 0.7144f, 0.6095f, 0.905f, 0.789f, 0.946f, 0.741f, 0.122f, 0.095f, 0, 0x8a6au },   // Glass Cathedral
    { 0.1165f, 0.9400f, 0.041f, 0.007f, 0.122f, 0.000f, 0.891f, 0.156f, 0, 0x8a95u },   // Subharmonic Deep
    { 0.6727f, 0.5564f, 0.796f, 0.871f, 0.898f, 0.844f, 0.129f, 0.088f, 0, 0x48a6au },   // Breath of Flutes
    { 0.1427f, 0.7541f, 0.054f, 0.129f, 0.054f, 0.102f, 0.973f, 0.143f, 0, 0x8a95u },   // Bohlen Night
    { 0.4798f, 0.8590f, 0.571f, 0.293f, 0.347f, 0.354f, 0.197f, 0.150f, 0, 0x8a14u },   // Otonal Shimmer
    { 0.3368f, 0.9274f, 0.687f, 0.204f, 0.184f, 0.014f, 0.231f, 0.163f, 0, 0xaa14u },   // Distant Storm
    { 0.5947f, 0.0714f, 0.776f, 0.694f, 0.633f, 0.776f, 0.245f, 0.000f, 0, 0x28622u },   // Dry Foreground Keys
    { 0.1943f, 0.6803f, 0.136f, 0.136f, 0.075f, 0.401f, 0.939f, 0.170f, 0, 0x18a85u },   // Sleep Concert II
    { 0.5856f, 0.6428f, 0.639f, 0.680f, 0.456f, 0.728f, 0.524f, 0.177f, 1, 0x8a20u },   // Midnight Pentatonic
    { 0.1088f, 0.8161f, 0.000f, 0.088f, 0.211f, 0.156f, 0.980f, 0.184f, 1, 0x18a95u },   // Deep Sleep Sub
    { 0.3292f, 0.7275f, 0.415f, 0.388f, 0.231f, 0.497f, 0.605f, 0.190f, 1, 0x8a00u },   // Dawn Drift
    { 0.7299f, 0.5017f, 0.850f, 0.905f, 0.503f, 0.925f, 0.381f, 0.197f, 1, 0x48a2au },   // Night Rain
    { 0.3994f, 0.7249f, 0.490f, 0.435f, 0.340f, 0.490f, 0.626f, 0.204f, 1, 0x8a00u },   // Slow Tide
    { 0.1200f, 0.7216f, 0.007f, 0.027f, 0.626f, 0.327f, 0.993f, 0.429f, 1, 0x18895u },   // Hypnos
    { 0.2164f, 0.9223f, 0.102f, 0.068f, 0.381f, 0.034f, 0.680f, 0.109f, 1, 0x8a15u },   // Warm Blanket
    { 0.6548f, 0.7553f, 0.925f, 0.231f, 0.823f, 0.592f, 0.034f, 0.116f, 1, 0x28a46u },   // Somnus Harmonics
    { 0.4702f, 0.7550f, 0.224f, 0.510f, 0.313f, 0.673f, 0.327f, 0.122f, 1, 0x8a01u },   // Breathing Dark
    { 0.1701f, 0.9073f, 0.061f, 0.048f, 0.061f, 0.041f, 0.803f, 0.129f, 1, 0x18a95u },   // Velvet Hours
    { 0.8447f, 0.5269f, 0.986f, 0.850f, 0.830f, 0.918f, 0.109f, 0.136f, 2, 0x8a6au },   // Ice Cathedral
    { 0.7736f, 0.5587f, 0.918f, 0.857f, 0.776f, 0.803f, 0.088f, 0.361f, 2, 0x4886au },   // Glass Choir
    { 0.5969f, 0.7161f, 0.762f, 0.578f, 0.558f, 0.551f, 0.190f, 0.367f, 2, 0x8802u },   // Crystal Bells
    { 0.4197f, 0.8078f, 0.265f, 0.476f, 0.707f, 0.245f, 0.599f, 0.374f, 2, 0x48851u },   // Wineglass Rim
    { 0.6044f, 0.8805f, 0.871f, 0.075f, 0.891f, 0.367f, 0.041f, 0.381f, 2, 0x28856u },   // High Organ
    { 0.3973f, 0.9304f, 0.626f, 0.000f, 0.844f, 0.020f, 0.075f, 0.388f, 2, 0x8854u },   // Stained Light
    { 0.2504f, 0.8435f, 0.177f, 0.197f, 0.163f, 0.279f, 0.571f, 0.395f, 2, 0x8815u },   // Frozen Chapel
    { 0.3015f, 0.8012f, 0.286f, 0.429f, 0.156f, 0.231f, 0.558f, 0.401f, 2, 0x8811u },   // Silver Threads
    { 0.6014f, 0.5989f, 0.789f, 0.707f, 0.517f, 0.755f, 0.388f, 0.408f, 2, 0x882au },   // Bright Pentatonic
    { 0.6236f, 0.6317f, 0.816f, 0.728f, 0.490f, 0.735f, 0.238f, 0.415f, 2, 0x882au },   // Prism
    { 0.0975f, 0.8943f, 0.020f, 0.054f, 0.000f, 0.061f, 0.871f, 0.422f, 3, 0x8895u },   // Abyss
    { 0.1691f, 0.8219f, 0.034f, 0.143f, 0.102f, 0.109f, 0.952f, 0.864f, 3, 0x8995u },   // Tectonic
    { 0.2897f, 0.8390f, 0.109f, 0.170f, 0.449f, 0.408f, 0.741f, 0.218f, 3, 0x48a85u },   // Whale Song
    { 0.6942f, 0.4500f, 0.823f, 0.891f, 0.789f, 0.932f, 0.850f, 0.224f, 3, 0x48aeau },   // Cave Water
    { 0.2748f, 0.8757f, 0.156f, 0.122f, 0.245f, 0.136f, 0.361f, 0.231f, 3, 0x8a15u },   // Undertow
    { 0.2185f, 0.8812f, 0.116f, 0.116f, 0.034f, 0.129f, 0.755f, 0.238f, 3, 0x8a95u },   // Bass Temple
    { 0.2065f, 0.8358f, 0.095f, 0.163f, 0.068f, 0.143f, 0.864f, 0.245f, 3, 0x8a95u },   // Slow Magma
    { 0.1414f, 0.7936f, 0.014f, 0.014f, 0.095f, 0.476f, 0.966f, 0.252f, 3, 0xa85u },   // Deep Space Hum
    { 0.6632f, 0.6328f, 0.694f, 0.755f, 0.653f, 0.762f, 0.177f, 0.259f, 3, 0x48a28u },   // Subterranean Choir
    { 0.2316f, 0.7787f, 0.163f, 0.252f, 0.109f, 0.293f, 0.823f, 0.265f, 3, 0x8a95u },   // Low Pythagorean
    { 0.5824f, 0.5295f, 0.252f, 0.776f, 0.571f, 0.796f, 0.796f, 0.272f, 4, 0x48aa9u },   // Shakuhachi Air
    { 0.7007f, 0.5284f, 0.830f, 0.864f, 0.762f, 0.830f, 0.095f, 0.279f, 4, 0x48a6au },   // Ocarina Clouds
    { 0.7906f, 0.4779f, 0.891f, 0.939f, 0.810f, 0.939f, 0.435f, 0.286f, 4, 0x48a6au },   // Bamboo Wind
    { 0.6499f, 0.6905f, 0.803f, 0.612f, 0.973f, 0.639f, 0.061f, 0.293f, 4, 0x49a42u },   // Alto Voices
    { 0.5247f, 0.8459f, 0.680f, 0.272f, 0.537f, 0.177f, 0.340f, 0.299f, 4, 0x9a14u },   // Boys Choir
    { 0.3690f, 0.5555f, 0.388f, 0.653f, 0.143f, 0.782f, 0.898f, 0.306f, 4, 0x98a0u },   // Throat Drone
    { 0.8245f, 0.4039f, 0.932f, 0.946f, 0.850f, 1.000f, 0.619f, 0.313f, 4, 0x4886au },   // Whispered
    { 0.4172f, 0.6396f, 0.503f, 0.490f, 0.272f, 0.667f, 0.735f, 0.320f, 4, 0x8880u },   // Reed Organ
    { 0.7110f, 0.5696f, 0.653f, 0.837f, 0.959f, 0.810f, 0.395f, 0.327f, 4, 0x48868u },   // Wooden Flutes
    { 0.6284f, 0.7885f, 0.782f, 0.456f, 0.816f, 0.680f, 0.020f, 0.333f, 4, 0x48842u },   // Sirens Far Away
    { 0.5015f, 0.7792f, 0.605f, 0.503f, 0.361f, 0.449f, 0.320f, 0.340f, 5, 0x8800u },   // Slendro Dusk
    { 0.2613f, 0.8049f, 0.143f, 0.177f, 0.694f, 0.122f, 0.932f, 0.347f, 5, 0x8895u },   // Bohlen Cathedral
    { 0.3508f, 0.8554f, 0.422f, 0.218f, 0.177f, 0.238f, 0.483f, 0.354f, 5, 0x8814u },   // Pythagorean Drone
    { 0.5397f, 0.8826f, 0.354f, 0.259f, 0.986f, 0.224f, 0.354f, 0.503f, 5, 0x8854u },   // Otonal Cloud
    { 0.3936f, 0.7732f, 0.429f, 0.374f, 0.429f, 0.374f, 0.687f, 0.497f, 5, 0x8810u },   // Subharmonic Bells
    { 0.5167f, 0.6221f, 0.707f, 0.544f, 0.327f, 0.701f, 0.517f, 0.490f, 5, 0x8822u },   // Harmonic Ladder
    { 0.2789f, 0.9400f, 0.184f, 0.020f, 0.585f, 0.027f, 0.116f, 0.483f, 5, 0x8815u },   // Seven Limit Garden
    { 0.3837f, 0.8775f, 0.333f, 0.245f, 0.129f, 0.265f, 0.333f, 0.476f, 5, 0x8814u },   // Minor Third Field
    { 0.4385f, 0.8689f, 0.327f, 0.306f, 0.660f, 0.252f, 0.531f, 0.469f, 5, 0x810u },   // Twelve Tone Fog
    { 0.4621f, 0.9006f, 0.755f, 0.211f, 0.435f, 0.088f, 0.293f, 0.463f, 5, 0x8816u },   // Pentatonic Rain
    { 0.3683f, 0.7003f, 0.435f, 0.415f, 0.286f, 0.469f, 0.565f, 0.456f, 6, 0x9800u },   // Shimmer Rise
    { 0.3140f, 0.8703f, 0.218f, 0.150f, 0.224f, 0.116f, 0.497f, 0.449f, 6, 0x9815u },   // Fifth Shimmer
    { 0.4694f, 0.5949f, 0.619f, 0.599f, 0.333f, 0.653f, 0.660f, 0.442f, 6, 0x9800u },   // Octave Below
    { 0.4933f, 0.8218f, 0.469f, 0.395f, 0.599f, 0.442f, 0.367f, 0.435f, 6, 0x8800u },   // Echo Canyon
    { 0.3323f, 0.4946f, 0.245f, 0.156f, 0.388f, 0.163f, 0.442f, 0.082f, 6, 0x8a15u },   // Ping Pong Drift
    { 0.3551f, 0.7828f, 0.299f, 0.633f, 0.082f, 0.299f, 0.279f, 0.510f, 6, 0x8811u },   // Rotating Sky
    { 0.4331f, 0.7706f, 0.259f, 0.463f, 0.980f, 0.259f, 0.844f, 0.531f, 6, 0x88d1u },   // Slow Chorus Field
    { 0.1816f, 0.8670f, 0.129f, 0.095f, 0.041f, 0.095f, 0.857f, 0.537f, 6, 0x8895u },   // Tape Echo Drone
    { 0.4384f, 0.7313f, 0.531f, 0.354f, 0.306f, 0.463f, 0.408f, 0.517f, 6, 0x9800u },   // Shimmer Cathedral
    { 0.3312f, 0.6865f, 0.517f, 0.347f, 0.265f, 0.415f, 0.694f, 0.524f, 6, 0x9800u },   // Nineteenth Above
    { 0.5074f, 0.5836f, 0.340f, 0.762f, 0.544f, 0.626f, 0.728f, 0.585f, 7, 0x9888u },   // Nebula Drift
    { 0.3872f, 0.6655f, 0.401f, 0.571f, 0.252f, 0.558f, 0.639f, 0.592f, 7, 0x9800u },   // Frozen Nebula
    { 0.5888f, 0.7871f, 0.646f, 0.619f, 0.878f, 0.218f, 0.347f, 0.599f, 7, 0x9850u },   // Alien Choir
    { 0.5391f, 0.7661f, 0.476f, 0.517f, 0.701f, 0.333f, 0.401f, 0.605f, 7, 0x1850u },   // Forbidden Planet
    { 0.1433f, 0.8569f, 0.082f, 0.061f, 0.088f, 0.048f, 0.925f, 0.612f, 7, 0x9895u },   // Hull Resonance
    { 0.9068f, 0.4607f, 1.000f, 0.973f, 0.646f, 0.959f, 0.156f, 0.619f, 7, 0x4982au },   // Signal From Deep Space
    { 0.4229f, 0.6004f, 0.238f, 0.735f, 0.551f, 0.381f, 0.816f, 0.626f, 7, 0x9899u },   // Event Horizon
    { 0.7671f, 0.4440f, 0.844f, 0.932f, 0.612f, 0.980f, 0.490f, 0.633f, 7, 0x4982au },   // Ion Wind
    { 0.4505f, 0.6611f, 0.558f, 0.626f, 0.170f, 0.619f, 0.449f, 0.639f, 7, 0x9800u },   // Cryo Chamber
    { 0.6155f, 0.7511f, 0.660f, 0.605f, 0.864f, 0.422f, 0.204f, 0.646f, 7, 0x1840u },   // Pulsar Field
    { 0.5672f, 0.8203f, 0.483f, 0.497f, 1.000f, 0.388f, 0.286f, 0.544f, 7, 0x9850u },   // Ring World
    { 0.6629f, 0.5166f, 0.769f, 0.925f, 0.605f, 0.912f, 0.585f, 0.551f, 7, 0x4982au },   // Solar Wind
    { 0.3373f, 0.8182f, 0.211f, 0.279f, 0.408f, 0.190f, 0.701f, 0.558f, 7, 0x9895u },   // Derelict Ship
    { 0.5440f, 0.7262f, 0.551f, 0.660f, 0.639f, 0.286f, 0.374f, 0.565f, 7, 0x9810u },   // Telepathy
    { 0.1914f, 0.6054f, 0.204f, 0.592f, 0.020f, 0.524f, 0.912f, 0.571f, 7, 0x9881u },   // Warp Core
    { 0.5011f, 0.7007f, 0.361f, 0.687f, 0.483f, 0.435f, 0.578f, 0.578f, 7, 0x9800u },   // Comet Tail
    { 0.5464f, 0.6483f, 0.497f, 0.748f, 0.592f, 0.599f, 0.544f, 0.714f, 7, 0x9908u },   // Andromeda
    { 0.5632f, 0.6101f, 0.728f, 0.667f, 0.367f, 0.721f, 0.469f, 0.707f, 7, 0x9922u },   // Ganymede Ice
    { 0.9005f, 0.4135f, 0.980f, 0.966f, 0.966f, 0.986f, 0.272f, 0.701f, 7, 0x4996au },   // Lost Transmission
    { 0.5068f, 0.7399f, 0.463f, 0.646f, 0.721f, 0.272f, 0.476f, 0.694f, 7, 0x9850u },   // Stellar Nursery
    { 0.4649f, 0.7942f, 0.537f, 0.537f, 0.524f, 0.204f, 0.456f, 0.687f, 7, 0x1810u },   // Xenomorph Hive
    { 0.5759f, 0.5686f, 0.313f, 0.816f, 0.673f, 0.694f, 0.769f, 0.680f, 7, 0x9888u },   // Zero Gravity
    { 0.2964f, 0.7053f, 0.633f, 0.265f, 0.204f, 0.197f, 0.810f, 0.673f, 7, 0x9894u },   // Monolith
    { 0.6156f, 0.6708f, 0.701f, 0.714f, 0.871f, 0.633f, 0.224f, 0.667f, 7, 0x984au },   // Quasar
    { 0.2287f, 0.6186f, 0.048f, 0.701f, 0.259f, 0.395f, 0.959f, 0.660f, 7, 0x9899u },   // Dark Matter
    { 0.4615f, 0.6992f, 0.367f, 0.531f, 0.415f, 0.456f, 0.503f, 0.653f, 7, 0x9800u },   // Orbital Decay
    { 0.4514f, 0.8315f, 0.395f, 0.333f, 0.422f, 0.361f, 0.306f, 0.735f, 7, 0x9910u },   // First Contact
    { 0.6173f, 0.5108f, 0.599f, 0.803f, 0.401f, 0.864f, 0.707f, 0.741f, 7, 0x499a8u },   // Plasma Sea
    { 0.8064f, 0.4391f, 0.912f, 0.952f, 0.796f, 0.973f, 0.537f, 0.721f, 7, 0x4996au },   // Void Whisper
    { 0.2618f, 0.6859f, 0.231f, 0.408f, 0.354f, 0.150f, 0.918f, 0.728f, 7, 0x9991u },   // Alien Cathedral
    { 0.2649f, 0.1052f, 0.197f, 0.320f, 0.197f, 0.517f, 0.776f, 0.020f, 8, 0x8681u },   // Warm Keys
    { 0.3059f, 0.0831f, 0.578f, 0.401f, 0.150f, 0.571f, 0.510f, 0.014f, 8, 0x8600u },   // Glass Keys
    { 0.3161f, 0.1311f, 0.272f, 0.340f, 0.857f, 0.184f, 0.837f, 0.048f, 8, 0x86d1u },   // Pad Keys
    { 0.6536f, 0.0600f, 0.612f, 0.823f, 0.884f, 0.823f, 0.163f, 0.041f, 8, 0x48668u },   // Flute Keys
    { 0.3414f, 0.1007f, 0.320f, 0.367f, 0.497f, 0.585f, 0.762f, 0.061f, 8, 0x8680u },   // Organ Keys
    { 0.4303f, 0.0805f, 0.381f, 0.741f, 0.565f, 0.612f, 0.748f, 0.068f, 8, 0x9688u },   // Cosmos Keys
    { 0.3744f, 0.1225f, 0.449f, 0.361f, 0.578f, 0.340f, 0.653f, 0.034f, 8, 0x9610u },   // Shimmer Keys
    { 0.1517f, 0.1020f, 0.088f, 0.190f, 0.007f, 0.531f, 0.830f, 0.027f, 8, 0x8685u },   // Sub Keys
    { 0.4139f, 0.1248f, 0.714f, 0.442f, 0.531f, 0.054f, 0.170f, 0.054f, 8, 0x9612u },   // Vowel Keys
    { 0.3632f, 0.0677f, 0.524f, 0.483f, 0.374f, 0.565f, 0.721f, 0.007f, 8, 0x9680u },   // Resonant Keys
    { 0.2793f, 0.7684f, 0.170f, 0.224f, 0.442f, 0.347f, 0.878f, 0.748f, 9, 0x18995u },   // All Night Arc
    { 0.5775f, 0.6816f, 0.544f, 0.585f, 0.619f, 0.660f, 0.415f, 0.755f, 9, 0x8900u },   // Tidal Hours
    { 0.2538f, 0.9093f, 0.122f, 0.082f, 0.510f, 0.068f, 0.646f, 0.762f, 9, 0x8915u },   // Slow Sunrise
    { 0.3501f, 0.6517f, 0.408f, 0.524f, 0.238f, 0.544f, 0.612f, 0.769f, 9, 0x9900u },   // Ninety Minute Cycle
    { 0.4201f, 0.6912f, 0.510f, 0.469f, 0.395f, 0.503f, 0.667f, 0.776f, 9, 0x8900u },   // REM Drift
    { 0.3804f, 0.8133f, 0.374f, 0.381f, 0.279f, 0.320f, 0.463f, 0.782f, 9, 0x8910u },   // Dream Corridor
    { 0.4067f, 0.8452f, 0.592f, 0.313f, 0.299f, 0.306f, 0.252f, 0.789f, 9, 0x8910u },   // Deep Night Harmonics
    { 0.5013f, 0.8923f, 0.347f, 0.238f, 0.782f, 0.211f, 0.218f, 0.796f, 9, 0x8954u },   // Long Otonal Night
    { 0.4787f, 0.6334f, 0.442f, 0.673f, 0.463f, 0.537f, 0.714f, 0.803f, 9, 0x9980u },   // Sleeping Nebula
    { 0.3193f, 0.7658f, 0.279f, 0.299f, 0.218f, 0.429f, 0.673f, 0.810f, 9, 0x8905u },   // Morning Fade
    { 0.8673f, 0.4577f, 0.966f, 0.993f, 0.687f, 0.857f, 0.313f, 0.816f, 10, 0x292au },   // Cluster Storm
    { 0.3023f, 0.9081f, 0.293f, 0.102f, 0.136f, 0.075f, 0.211f, 0.823f, 10, 0x915u },   // Micro Cluster
    { 0.5383f, 0.6871f, 0.565f, 0.565f, 0.837f, 0.510f, 0.551f, 0.830f, 10, 0x9940u },   // Rising Swarm
    { 0.2325f, 0.5792f, 0.068f, 0.286f, 0.116f, 0.748f, 0.946f, 0.837f, 10, 0x489a5u },   // Thunder Head
    { 0.5377f, 0.5581f, 0.306f, 0.810f, 0.748f, 0.646f, 0.782f, 0.844f, 10, 0x99c8u },   // Granular Sky
    { 0.9400f, 0.4167f, 0.993f, 1.000f, 0.939f, 0.952f, 0.184f, 0.850f, 10, 0xa96au },   // Inharmonic Field
    { 0.5759f, 0.7497f, 0.585f, 0.558f, 0.714f, 0.578f, 0.429f, 0.857f, 10, 0x940u },   // Dissonant Cathedral
    { 0.6920f, 0.4897f, 0.673f, 0.844f, 0.803f, 0.966f, 0.633f, 0.871f, 10, 0x40968u },   // White Storm
    { 0.6388f, 0.5859f, 0.884f, 0.721f, 0.320f, 0.769f, 0.054f, 0.878f, 11, 0xc92au },   // Vocal Morph Choir
    { 0.5300f, 0.8067f, 0.748f, 0.184f, 0.190f, 0.605f, 0.048f, 0.891f, 11, 0xc906u },   // Glass Table Drift
    { 0.2567f, 0.6467f, 0.735f, 0.109f, 0.048f, 0.313f, 0.884f, 0.884f, 11, 0xc996u },   // Organ Mixture Cloud
    { 0.8071f, 0.5145f, 0.946f, 0.912f, 0.993f, 0.871f, 0.259f, 0.898f, 11, 0xe96au },   // Metal Field
    { 0.7003f, 0.6465f, 0.939f, 0.639f, 0.667f, 0.707f, 0.136f, 0.905f, 11, 0xc922u },   // FM Bell Drone
    { 0.0600f, 0.6607f, 0.027f, 0.041f, 0.014f, 0.082f, 0.986f, 0.912f, 11, 0xc995u },   // Slow FM Tide
    { 0.8299f, 0.4709f, 0.952f, 0.986f, 0.735f, 0.878f, 0.265f, 0.918f, 11, 0xe96au },   // Feedback Hiss
    { 0.0653f, 0.0758f, 0.075f, 0.034f, 0.027f, 0.170f, 1.000f, 0.075f, 11, 0x2c695u },   // Three Voices, One Key
    { 0.7873f, 0.5962f, 0.878f, 0.796f, 0.952f, 0.837f, 0.014f, 0.925f, 12, 0x896au },   // Morphing Vowels
    { 0.7675f, 0.5142f, 0.864f, 0.918f, 0.925f, 0.905f, 0.102f, 0.932f, 12, 0x896au },   // Choir Behind Glass
    { 0.7484f, 0.5892f, 0.810f, 0.830f, 0.912f, 0.850f, 0.027f, 0.939f, 12, 0x896au },   // Nasal Drone
    { 0.7319f, 0.4621f, 0.857f, 0.898f, 0.918f, 0.898f, 0.299f, 0.946f, 12, 0x896au },   // Filter Tide
    { 0.5071f, 0.6614f, 0.190f, 0.551f, 0.932f, 0.714f, 0.789f, 0.952f, 12, 0x89e1u },   // Phase Field
    { 0.6773f, 0.5958f, 0.667f, 0.769f, 0.755f, 0.789f, 0.143f, 0.959f, 12, 0x8968u },   // Comb Cathedral
    { 0.8613f, 0.4186f, 0.973f, 0.980f, 0.680f, 0.993f, 0.150f, 0.966f, 12, 0x4892au },   // Notch Winds
    { 0.7382f, 0.5409f, 0.837f, 0.878f, 0.769f, 0.884f, 0.068f, 0.973f, 12, 0x896au },   // String Body
    { 0.8131f, 0.5550f, 0.898f, 0.884f, 0.728f, 0.891f, 0.000f, 0.980f, 12, 0x896au },   // Struck Bars
    { 0.8708f, 0.4972f, 0.959f, 0.959f, 0.469f, 0.946f, 0.007f, 0.986f, 12, 0x892au },   // Glass Needles
    { 0.4999f, 0.9319f, 0.741f, 0.449f, 0.905f, 0.007f, 0.082f, 0.993f, 12, 0x48952u },   // Harmonic Sieve
    { 0.6344f, 0.5465f, 0.721f, 0.782f, 0.741f, 0.816f, 0.422f, 1.000f, 12, 0x896au },   // Endless Resonance
};
}

int builtinPresetMetaCount() { return static_cast<int>(sizeof(kMeta) / sizeof(kMeta[0])); }
const PresetMeta& builtinPresetMeta(int index) { static const PresetMeta none = { 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0, 0 }; return (index >= 0 && index < builtinPresetMetaCount()) ? kMeta[index] : none; }
int builtinPresetFamilyCount() { return static_cast<int>(sizeof(kFamilies) / sizeof(kFamilies[0])); }
const char* builtinPresetFamilyName(int family) { return (family >= 0 && family < builtinPresetFamilyCount()) ? kFamilies[family] : ""; }
const char* presetTagName(int bit) { return (bit >= 0 && bit < kNumPresetTags) ? kTagNames[bit] : ""; }

} // namespace ambient
