// Generated by Tools/preset_map.py -- do not edit. Measured from renders of every preset.
#include "ambient/PresetMeta.h"
#include "ambient/Presets.h"

namespace ambient {

namespace {
const char* const kFamilies[] = {
    "originals",
    "sleep / night",
    "cathedral / glass",
    "deep / sub / dark",
    "breath / flute / voice",
    "exotic scales",
    "shimmer / delay / motion",
    "cosmos / science fiction",
    "playable keys (brain off)",
    "long-form night arcs",
    "storm / cluster / texture",
    "sources (wavetable, FM, feedback)",
    "z-plane / morphing filter",
    "granular",
    "noise",
    "rich studies",
};
const char* const kTagNames[kNumPresetTags] = {
    "Dark", "Bright", "Calm", "Moving", "Tonal", "Noisy", "Wide", "Bass", "Dense", "Sparse", "Keys", "Generative", "Cosmos", "Feedback", "Sources", "JustIntonation", "Sub", "Stack", "Air"
};
const PresetMeta kMeta[] = {
    { 0.4094f, 0.5604f, 0.424f, 0.407f, 0.311f, 0.418f, 0.655f, 0.085f, 0, 0x8a00u },   // Init
    { 0.3523f, 0.6329f, 0.141f, 0.333f, 0.463f, 0.599f, 0.904f, 0.175f, 0, 0x18a81u },   // Sleep Concert
    { 0.7296f, 0.2949f, 0.898f, 0.734f, 0.938f, 0.644f, 0.141f, 0.079f, 0, 0x8a4au },   // Glass Cathedral
    { 0.1901f, 0.4119f, 0.051f, 0.006f, 0.136f, 0.000f, 0.881f, 0.130f, 0, 0x8a95u },   // Subharmonic Deep
    { 0.7446f, 0.4514f, 0.763f, 0.825f, 0.876f, 0.791f, 0.147f, 0.073f, 0, 0x48a6au },   // Breath of Flutes
    { 0.2225f, 0.7476f, 0.056f, 0.102f, 0.051f, 0.090f, 0.960f, 0.119f, 0, 0x8a95u },   // Bohlen Night
    { 0.4691f, 0.3342f, 0.469f, 0.266f, 0.339f, 0.311f, 0.220f, 0.124f, 0, 0x8a14u },   // Otonal Shimmer
    { 0.3153f, 0.2685f, 0.610f, 0.169f, 0.153f, 0.011f, 0.322f, 0.136f, 0, 0xaa14u },   // Distant Storm
    { 0.5896f, 0.1087f, 0.751f, 0.605f, 0.605f, 0.689f, 0.232f, 0.000f, 0, 0x28602u },   // Dry Foreground Keys
    { 0.2550f, 0.7250f, 0.130f, 0.141f, 0.090f, 0.362f, 0.955f, 0.141f, 0, 0x18a95u },   // Sleep Concert II
    { 0.5833f, 0.5240f, 0.582f, 0.588f, 0.412f, 0.638f, 0.554f, 0.147f, 1, 0x8a00u },   // Midnight Pentatonic
    { 0.1517f, 0.7584f, 0.006f, 0.073f, 0.175f, 0.136f, 0.966f, 0.153f, 1, 0x18a95u },   // Deep Sleep Sub
    { 0.3962f, 0.5187f, 0.407f, 0.390f, 0.237f, 0.424f, 0.667f, 0.158f, 1, 0x8a00u },   // Dawn Drift
    { 0.7401f, 0.6413f, 0.836f, 0.859f, 0.514f, 0.910f, 0.418f, 0.164f, 1, 0x48a2au },   // Night Rain
    { 0.4343f, 0.5297f, 0.446f, 0.424f, 0.356f, 0.429f, 0.684f, 0.169f, 1, 0x8a00u },   // Slow Tide
    { 0.1846f, 0.7364f, 0.011f, 0.023f, 0.661f, 0.322f, 0.983f, 0.356f, 1, 0x18895u },   // Hypnos
    { 0.2734f, 0.3332f, 0.107f, 0.062f, 0.362f, 0.028f, 0.689f, 0.090f, 1, 0x8a15u },   // Warm Blanket
    { 0.6768f, 0.2341f, 0.910f, 0.203f, 0.814f, 0.463f, 0.056f, 0.096f, 1, 0x28a46u },   // Somnus Harmonics
    { 0.4596f, 0.4470f, 0.209f, 0.446f, 0.322f, 0.582f, 0.333f, 0.102f, 1, 0x8a01u },   // Breathing Dark
    { 0.2261f, 0.5647f, 0.062f, 0.040f, 0.068f, 0.034f, 0.802f, 0.107f, 1, 0x18a95u },   // Velvet Hours
    { 0.8163f, 0.4146f, 0.989f, 0.802f, 0.825f, 0.864f, 0.130f, 0.113f, 2, 0x8a6au },   // Ice Cathedral
    { 0.7506f, 0.4025f, 0.915f, 0.819f, 0.780f, 0.768f, 0.113f, 0.299f, 2, 0x48a6au },   // Glass Choir
    { 0.5349f, 0.3599f, 0.684f, 0.463f, 0.469f, 0.379f, 0.373f, 0.305f, 2, 0x8810u },   // Crystal Bells
    { 0.4088f, 0.3031f, 0.220f, 0.367f, 0.672f, 0.153f, 0.610f, 0.311f, 2, 0x48811u },   // Wineglass Rim
    { 0.6176f, 0.2255f, 0.825f, 0.056f, 0.853f, 0.282f, 0.062f, 0.316f, 2, 0x28856u },   // High Organ
    { 0.4226f, 0.2092f, 0.565f, 0.000f, 0.808f, 0.017f, 0.096f, 0.322f, 2, 0x8854u },   // Stained Light
    { 0.2969f, 0.5155f, 0.164f, 0.192f, 0.141f, 0.271f, 0.588f, 0.328f, 2, 0x8815u },   // Frozen Chapel
    { 0.3319f, 0.5340f, 0.266f, 0.384f, 0.158f, 0.203f, 0.582f, 0.333f, 2, 0x8811u },   // Silver Threads
    { 0.6054f, 0.4903f, 0.729f, 0.599f, 0.486f, 0.650f, 0.412f, 0.339f, 2, 0x8802u },   // Bright Pentatonic
    { 0.6552f, 0.4124f, 0.791f, 0.644f, 0.424f, 0.627f, 0.254f, 0.345f, 2, 0x8802u },   // Prism
    { 0.1580f, 0.7070f, 0.028f, 0.045f, 0.006f, 0.051f, 0.847f, 0.350f, 3, 0x8895u },   // Abyss
    { 0.2239f, 0.7005f, 0.045f, 0.153f, 0.102f, 0.107f, 0.949f, 0.718f, 3, 0x8995u },   // Tectonic
    { 0.3110f, 0.4785f, 0.102f, 0.147f, 0.407f, 0.328f, 0.763f, 0.181f, 3, 0x48a95u },   // Whale Song
    { 0.7106f, 0.7053f, 0.802f, 0.853f, 0.757f, 0.915f, 0.814f, 0.186f, 3, 0x48aeau },   // Cave Water
    { 0.3336f, 0.3846f, 0.147f, 0.119f, 0.226f, 0.124f, 0.379f, 0.192f, 3, 0x8a15u },   // Undertow
    { 0.2537f, 0.6275f, 0.113f, 0.113f, 0.045f, 0.119f, 0.768f, 0.198f, 3, 0x8a95u },   // Bass Temple
    { 0.2666f, 0.5901f, 0.096f, 0.164f, 0.085f, 0.130f, 0.831f, 0.203f, 3, 0x8a95u },   // Slow Magma
    { 0.1899f, 0.6802f, 0.023f, 0.017f, 0.113f, 0.412f, 0.944f, 0.209f, 3, 0xa85u },   // Deep Space Hum
    { 0.6491f, 0.3732f, 0.661f, 0.667f, 0.638f, 0.684f, 0.181f, 0.215f, 3, 0x48a00u },   // Subterranean Choir
    { 0.3049f, 0.6244f, 0.169f, 0.249f, 0.107f, 0.288f, 0.785f, 0.220f, 3, 0x8a95u },   // Low Pythagorean
    { 0.5463f, 0.6365f, 0.181f, 0.706f, 0.531f, 0.729f, 0.797f, 0.226f, 4, 0x48aa9u },   // Shakuhachi Air
    { 0.7059f, 0.4429f, 0.774f, 0.814f, 0.763f, 0.774f, 0.119f, 0.232f, 4, 0x48a6au },   // Ocarina Clouds
    { 0.7856f, 0.6507f, 0.864f, 0.910f, 0.797f, 0.932f, 0.446f, 0.237f, 4, 0x48a6au },   // Bamboo Wind
    { 0.6435f, 0.2555f, 0.768f, 0.525f, 0.972f, 0.542f, 0.090f, 0.243f, 4, 0x49a42u },   // Alto Voices
    { 0.4648f, 0.2628f, 0.593f, 0.226f, 0.497f, 0.102f, 0.345f, 0.249f, 4, 0x9a14u },   // Boys Choir
    { 0.4145f, 0.6789f, 0.435f, 0.576f, 0.164f, 0.706f, 0.870f, 0.254f, 4, 0x9aa0u },   // Throat Drone
    { 0.8462f, 0.7161f, 0.927f, 0.915f, 0.847f, 0.983f, 0.650f, 0.260f, 4, 0x48a6au },   // Whispered
    { 0.4304f, 0.5940f, 0.441f, 0.435f, 0.249f, 0.576f, 0.751f, 0.266f, 4, 0x8a80u },   // Reed Organ
    { 0.6907f, 0.4955f, 0.571f, 0.768f, 0.955f, 0.763f, 0.407f, 0.271f, 4, 0x48a68u },   // Wooden Flutes
    { 0.5763f, 0.1951f, 0.667f, 0.215f, 0.819f, 0.073f, 0.028f, 0.277f, 4, 0x48a54u },   // Sirens Far Away
    { 0.4958f, 0.3665f, 0.503f, 0.356f, 0.345f, 0.260f, 0.339f, 0.282f, 5, 0x8a10u },   // Slendro Dusk
    { 0.2829f, 0.5526f, 0.136f, 0.181f, 0.701f, 0.113f, 0.927f, 0.288f, 5, 0x8ad5u },   // Bohlen Cathedral
    { 0.3489f, 0.4669f, 0.379f, 0.209f, 0.181f, 0.220f, 0.531f, 0.294f, 5, 0x8a14u },   // Pythagorean Drone
    { 0.5345f, 0.2322f, 0.311f, 0.243f, 0.966f, 0.192f, 0.356f, 0.418f, 5, 0x8854u },   // Otonal Cloud
    { 0.3935f, 0.4792f, 0.299f, 0.288f, 0.401f, 0.226f, 0.746f, 0.412f, 5, 0x8895u },   // Subharmonic Bells
    { 0.5327f, 0.5406f, 0.576f, 0.429f, 0.254f, 0.571f, 0.559f, 0.407f, 5, 0x8800u },   // Harmonic Ladder
    { 0.3365f, 0.2335f, 0.153f, 0.011f, 0.582f, 0.023f, 0.136f, 0.401f, 5, 0x8815u },   // Seven Limit Garden
    { 0.3454f, 0.4224f, 0.305f, 0.237f, 0.124f, 0.232f, 0.316f, 0.395f, 5, 0x8814u },   // Minor Third Field
    { 0.4295f, 0.3370f, 0.288f, 0.277f, 0.576f, 0.215f, 0.565f, 0.390f, 5, 0x815u },   // Twelve Tone Fog
    { 0.3713f, 0.3160f, 0.655f, 0.198f, 0.243f, 0.056f, 0.469f, 0.384f, 5, 0x8814u },   // Pentatonic Rain
    { 0.4202f, 0.4499f, 0.412f, 0.395f, 0.305f, 0.407f, 0.605f, 0.379f, 6, 0x9800u },   // Shimmer Rise
    { 0.3416f, 0.3422f, 0.198f, 0.136f, 0.220f, 0.096f, 0.508f, 0.373f, 6, 0x9815u },   // Fifth Shimmer
    { 0.5095f, 0.5085f, 0.542f, 0.520f, 0.316f, 0.548f, 0.678f, 0.367f, 6, 0x9800u },   // Octave Below
    { 0.5083f, 0.3289f, 0.328f, 0.328f, 0.571f, 0.345f, 0.492f, 0.362f, 6, 0x8810u },   // Echo Canyon
    { 0.3530f, 0.2809f, 0.226f, 0.158f, 0.333f, 0.147f, 0.520f, 0.068f, 6, 0x8a15u },   // Ping Pong Drift
    { 0.3831f, 0.5901f, 0.277f, 0.542f, 0.079f, 0.254f, 0.282f, 0.424f, 6, 0x8811u },   // Rotating Sky
    { 0.4849f, 0.4045f, 0.249f, 0.412f, 0.960f, 0.243f, 0.853f, 0.441f, 6, 0x88d1u },   // Slow Chorus Field
    { 0.2352f, 0.6625f, 0.124f, 0.079f, 0.056f, 0.085f, 0.859f, 0.446f, 6, 0x8895u },   // Tape Echo Drone
    { 0.4171f, 0.3746f, 0.492f, 0.339f, 0.266f, 0.401f, 0.429f, 0.429f, 6, 0x9800u },   // Shimmer Cathedral
    { 0.3725f, 0.3917f, 0.452f, 0.311f, 0.282f, 0.356f, 0.701f, 0.435f, 6, 0x9890u },   // Nineteenth Above
    { 0.5489f, 0.5044f, 0.322f, 0.723f, 0.537f, 0.554f, 0.740f, 0.486f, 7, 0x9888u },   // Nebula Drift
    { 0.4323f, 0.4880f, 0.401f, 0.508f, 0.294f, 0.514f, 0.695f, 0.492f, 7, 0x9800u },   // Frozen Nebula
    { 0.6050f, 0.2648f, 0.621f, 0.559f, 0.881f, 0.209f, 0.367f, 0.497f, 7, 0x9850u },   // Alien Choir
    { 0.5150f, 0.2667f, 0.373f, 0.458f, 0.678f, 0.277f, 0.424f, 0.503f, 7, 0x1810u },   // Forbidden Planet
    { 0.2214f, 0.6040f, 0.085f, 0.051f, 0.096f, 0.040f, 0.910f, 0.508f, 7, 0x9895u },   // Hull Resonance
    { 0.8892f, 0.6012f, 1.000f, 0.955f, 0.599f, 0.944f, 0.186f, 0.514f, 7, 0x4982au },   // Signal From Deep Space
    { 0.4701f, 0.5127f, 0.232f, 0.650f, 0.542f, 0.350f, 0.819f, 0.520f, 7, 0x9891u },   // Event Horizon
    { 0.7799f, 0.6913f, 0.819f, 0.893f, 0.593f, 0.960f, 0.514f, 0.525f, 7, 0x4982au },   // Ion Wind
    { 0.4912f, 0.5462f, 0.514f, 0.548f, 0.169f, 0.531f, 0.463f, 0.531f, 7, 0x9800u },   // Cryo Chamber
    { 0.5550f, 0.2661f, 0.525f, 0.497f, 0.983f, 0.198f, 0.542f, 0.537f, 7, 0x1850u },   // Pulsar Field
    { 0.5791f, 0.2346f, 0.384f, 0.418f, 0.989f, 0.339f, 0.288f, 0.452f, 7, 0x9850u },   // Ring World
    { 0.6973f, 0.6266f, 0.746f, 0.876f, 0.610f, 0.881f, 0.638f, 0.458f, 7, 0x4982au },   // Solar Wind
    { 0.3835f, 0.3537f, 0.203f, 0.271f, 0.373f, 0.169f, 0.616f, 0.463f, 7, 0x9815u },   // Derelict Ship
    { 0.5812f, 0.2965f, 0.497f, 0.582f, 0.616f, 0.266f, 0.395f, 0.469f, 7, 0x9810u },   // Telepathy
    { 0.2869f, 0.7014f, 0.237f, 0.531f, 0.023f, 0.486f, 0.876f, 0.475f, 7, 0x9881u },   // Warp Core
    { 0.5244f, 0.3984f, 0.339f, 0.616f, 0.458f, 0.390f, 0.621f, 0.480f, 7, 0x9810u },   // Comet Tail
    { 0.5762f, 0.4172f, 0.429f, 0.672f, 0.588f, 0.520f, 0.571f, 0.593f, 7, 0x9800u },   // Andromeda
    { 0.5650f, 0.4682f, 0.627f, 0.554f, 0.350f, 0.610f, 0.486f, 0.588f, 7, 0x9800u },   // Ganymede Ice
    { 0.9097f, 0.6388f, 0.983f, 0.960f, 0.927f, 0.966f, 0.294f, 0.582f, 7, 0x4986au },   // Lost Transmission
    { 0.5366f, 0.3011f, 0.367f, 0.565f, 0.706f, 0.249f, 0.503f, 0.576f, 7, 0x9850u },   // Stellar Nursery
    { 0.4875f, 0.2952f, 0.480f, 0.469f, 0.492f, 0.175f, 0.475f, 0.571f, 7, 0x1810u },   // Xenomorph Hive
    { 0.5764f, 0.5630f, 0.282f, 0.797f, 0.667f, 0.593f, 0.780f, 0.565f, 7, 0x9889u },   // Zero Gravity
    { 0.3590f, 0.5052f, 0.616f, 0.254f, 0.203f, 0.186f, 0.808f, 0.559f, 7, 0x9894u },   // Monolith
    { 0.6307f, 0.2969f, 0.672f, 0.633f, 0.870f, 0.559f, 0.237f, 0.554f, 7, 0x9840u },   // Quasar
    { 0.2942f, 0.6625f, 0.068f, 0.638f, 0.288f, 0.384f, 0.938f, 0.548f, 7, 0x9891u },   // Dark Matter
    { 0.4457f, 0.4100f, 0.333f, 0.475f, 0.390f, 0.395f, 0.548f, 0.542f, 7, 0x9810u },   // Orbital Decay
    { 0.4483f, 0.3005f, 0.345f, 0.305f, 0.395f, 0.305f, 0.305f, 0.610f, 7, 0x9810u },   // First Contact
    { 0.6282f, 0.6483f, 0.559f, 0.763f, 0.384f, 0.825f, 0.723f, 0.616f, 7, 0x498a8u },   // Plasma Sea
    { 0.8193f, 0.6870f, 0.921f, 0.932f, 0.842f, 0.955f, 0.576f, 0.599f, 7, 0x4986au },   // Void Whisper
    { 0.3059f, 0.5848f, 0.215f, 0.345f, 0.328f, 0.141f, 0.915f, 0.605f, 7, 0x9891u },   // Alien Cathedral
    { 0.2923f, 0.1486f, 0.186f, 0.294f, 0.198f, 0.452f, 0.774f, 0.017f, 8, 0x8685u },   // Warm Keys
    { 0.3318f, 0.1456f, 0.508f, 0.373f, 0.147f, 0.497f, 0.525f, 0.011f, 8, 0x8600u },   // Glass Keys
    { 0.3475f, 0.0907f, 0.254f, 0.316f, 0.859f, 0.164f, 0.842f, 0.040f, 8, 0x86d1u },   // Pad Keys
    { 0.6507f, 0.1217f, 0.554f, 0.791f, 0.864f, 0.785f, 0.164f, 0.034f, 8, 0x48668u },   // Flute Keys
    { 0.3714f, 0.1451f, 0.294f, 0.362f, 0.452f, 0.508f, 0.757f, 0.051f, 8, 0x8681u },   // Organ Keys
    { 0.4402f, 0.1186f, 0.362f, 0.655f, 0.559f, 0.525f, 0.734f, 0.056f, 8, 0x9680u },   // Cosmos Keys
    { 0.3898f, 0.0799f, 0.390f, 0.350f, 0.565f, 0.316f, 0.644f, 0.028f, 8, 0x9610u },   // Shimmer Keys
    { 0.2087f, 0.1987f, 0.090f, 0.186f, 0.011f, 0.458f, 0.836f, 0.023f, 8, 0x8685u },   // Sub Keys
    { 0.4241f, 0.0600f, 0.695f, 0.401f, 0.480f, 0.045f, 0.169f, 0.045f, 8, 0x9610u },   // Vowel Keys
    { 0.4003f, 0.1181f, 0.463f, 0.441f, 0.367f, 0.492f, 0.718f, 0.006f, 8, 0x9680u },   // Resonant Keys
    { 0.3451f, 0.5790f, 0.158f, 0.220f, 0.429f, 0.333f, 0.864f, 0.621f, 9, 0x18895u },   // All Night Arc
    { 0.5700f, 0.3781f, 0.486f, 0.514f, 0.627f, 0.565f, 0.435f, 0.627f, 9, 0x8800u },   // Tidal Hours
    { 0.3146f, 0.3104f, 0.119f, 0.068f, 0.508f, 0.068f, 0.633f, 0.633f, 9, 0x8815u },   // Slow Sunrise
    { 0.3797f, 0.4421f, 0.395f, 0.480f, 0.260f, 0.469f, 0.672f, 0.638f, 9, 0x9800u },   // Ninety Minute Cycle
    { 0.4862f, 0.4765f, 0.458f, 0.452f, 0.379f, 0.446f, 0.712f, 0.644f, 9, 0x8880u },   // REM Drift
    { 0.4062f, 0.4126f, 0.350f, 0.379f, 0.271f, 0.299f, 0.497f, 0.650f, 9, 0x8810u },   // Dream Corridor
    { 0.4566f, 0.3719f, 0.537f, 0.260f, 0.299f, 0.237f, 0.243f, 0.655f, 9, 0x8814u },   // Deep Night Harmonics
    { 0.4923f, 0.2343f, 0.316f, 0.232f, 0.831f, 0.181f, 0.226f, 0.661f, 9, 0x8854u },   // Long Otonal Night
    { 0.5020f, 0.4402f, 0.418f, 0.610f, 0.446f, 0.480f, 0.729f, 0.667f, 9, 0x9880u },   // Sleeping Nebula
    { 0.3691f, 0.5476f, 0.271f, 0.282f, 0.215f, 0.373f, 0.706f, 0.672f, 9, 0x8895u },   // Morning Fade
    { 0.8701f, 0.6391f, 0.966f, 0.994f, 0.791f, 0.814f, 0.271f, 0.678f, 10, 0x286au },   // Cluster Storm
    { 0.3047f, 0.3575f, 0.260f, 0.085f, 0.130f, 0.062f, 0.215f, 0.684f, 10, 0x815u },   // Micro Cluster
    { 0.5623f, 0.3313f, 0.475f, 0.492f, 0.802f, 0.435f, 0.593f, 0.689f, 10, 0x9840u },   // Rising Swarm
    { 0.2828f, 0.7532f, 0.079f, 0.299f, 0.119f, 0.667f, 0.932f, 0.695f, 10, 0x48885u },   // Thunder Head
    { 0.5403f, 0.5795f, 0.243f, 0.757f, 0.621f, 0.537f, 0.825f, 0.701f, 10, 0x9989u },   // Granular Sky
    { 0.9400f, 0.6667f, 0.994f, 1.000f, 0.932f, 0.938f, 0.153f, 0.706f, 10, 0xa96au },   // Inharmonic Field
    { 0.6016f, 0.3357f, 0.531f, 0.486f, 0.712f, 0.475f, 0.452f, 0.712f, 10, 0x940u },   // Dissonant Cathedral
    { 0.7052f, 0.6654f, 0.633f, 0.808f, 0.774f, 0.949f, 0.661f, 0.723f, 10, 0x40968u },   // White Storm
    { 0.6539f, 0.5263f, 0.876f, 0.621f, 0.277f, 0.678f, 0.073f, 0.729f, 11, 0xc902u },   // Vocal Morph Choir
    { 0.5414f, 0.4361f, 0.723f, 0.175f, 0.186f, 0.441f, 0.068f, 0.740f, 11, 0xc906u },   // Glass Table Drift
    { 0.3231f, 0.7174f, 0.706f, 0.107f, 0.062f, 0.294f, 0.887f, 0.734f, 11, 0xc996u },   // Organ Mixture Cloud
    { 0.8164f, 0.5481f, 0.949f, 0.847f, 1.000f, 0.819f, 0.266f, 0.746f, 11, 0xe96au },   // Metal Field
    { 0.6913f, 0.3656f, 0.938f, 0.537f, 0.695f, 0.588f, 0.192f, 0.751f, 11, 0xc902u },   // FM Bell Drone
    { 0.1361f, 0.8191f, 0.034f, 0.034f, 0.017f, 0.079f, 0.977f, 0.757f, 11, 0xc995u },   // Slow FM Tide
    { 0.8596f, 0.6782f, 0.955f, 0.983f, 0.785f, 0.836f, 0.249f, 0.763f, 11, 0xe96au },   // Feedback Hiss
    { 0.1397f, 0.3214f, 0.073f, 0.028f, 0.028f, 0.158f, 0.989f, 0.062f, 11, 0x2c695u },   // Three Voices, One Key
    { 0.7649f, 0.3130f, 0.853f, 0.740f, 0.949f, 0.797f, 0.023f, 0.768f, 12, 0x896au },   // Morphing Vowels
    { 0.7765f, 0.4748f, 0.842f, 0.870f, 0.944f, 0.853f, 0.124f, 0.774f, 12, 0x896au },   // Choir Behind Glass
    { 0.7480f, 0.3630f, 0.785f, 0.785f, 0.904f, 0.808f, 0.034f, 0.780f, 12, 0x896au },   // Nasal Drone
    { 0.7577f, 0.5394f, 0.831f, 0.842f, 0.915f, 0.859f, 0.299f, 0.785f, 12, 0x896au },   // Filter Tide
    { 0.5256f, 0.4724f, 0.175f, 0.503f, 0.994f, 0.616f, 0.791f, 0.791f, 12, 0x89c1u },   // Phase Field
    { 0.6941f, 0.4051f, 0.644f, 0.712f, 0.740f, 0.746f, 0.158f, 0.797f, 12, 0x8968u },   // Comb Cathedral
    { 0.8962f, 0.6933f, 0.972f, 0.966f, 0.655f, 0.972f, 0.175f, 0.802f, 12, 0x4892au },   // Notch Winds
    { 0.7396f, 0.4915f, 0.797f, 0.831f, 0.746f, 0.831f, 0.107f, 0.808f, 12, 0x896au },   // String Body
    { 0.7786f, 0.4311f, 0.887f, 0.836f, 0.633f, 0.842f, 0.006f, 0.814f, 12, 0x892au },   // Struck Bars
    { 0.8489f, 0.6057f, 0.960f, 0.938f, 0.441f, 0.927f, 0.011f, 0.819f, 12, 0x892au },   // Glass Needles
    { 0.5099f, 0.1988f, 0.718f, 0.322f, 0.887f, 0.006f, 0.102f, 0.825f, 12, 0x48952u },   // Harmonic Sieve
    { 0.6886f, 0.5454f, 0.701f, 0.751f, 0.751f, 0.780f, 0.441f, 0.831f, 12, 0x896au },   // Endless Resonance
    { 0.6085f, 0.6140f, 0.599f, 0.678f, 0.503f, 0.695f, 0.480f, 0.836f, 13, 0xc900u },   // Frozen Grain
    { 0.7709f, 0.6138f, 0.881f, 0.898f, 0.689f, 0.898f, 0.079f, 0.842f, 13, 0xc92au },   // Grain Field
    { 0.7417f, 0.6808f, 0.859f, 0.881f, 0.192f, 0.876f, 0.085f, 0.847f, 13, 0xc92au },   // Grain Swarm
    { 0.6508f, 0.6071f, 0.689f, 0.695f, 0.554f, 0.740f, 0.384f, 0.853f, 13, 0xc920u },   // Slow Scatter
    { 0.7109f, 0.3298f, 0.808f, 0.593f, 0.893f, 0.655f, 0.040f, 0.859f, 13, 0x2c942u },   // Grain Choir
    { 0.7935f, 0.5804f, 0.870f, 0.887f, 0.768f, 0.887f, 0.051f, 0.864f, 13, 0xc96au },   // Pulverised
    { 0.1652f, 0.8612f, 0.017f, 0.090f, 0.034f, 0.734f, 0.994f, 0.870f, 13, 0x1c9a5u },   // Grain Cavern
    { 0.6527f, 0.5659f, 0.712f, 0.718f, 0.520f, 0.751f, 0.328f, 0.876f, 13, 0xd92au },   // Grain Shimmer
    { 0.6859f, 0.5875f, 0.734f, 0.729f, 0.684f, 0.757f, 0.203f, 0.881f, 13, 0xe92au },   // Grain Tape
    { 0.7246f, 0.5960f, 0.757f, 0.774f, 0.836f, 0.802f, 0.390f, 0.887f, 13, 0xc96au },   // Grain Horizon
    { 0.6958f, 0.7904f, 0.638f, 0.921f, 0.418f, 0.921f, 0.893f, 0.893f, 14, 0xc9a8u },   // Pink Bed
    { 0.0600f, 0.9400f, 0.000f, 0.130f, 0.000f, 0.672f, 1.000f, 0.898f, 14, 0x1c985u },   // Brown Floor
    { 0.8205f, 0.7462f, 0.977f, 0.972f, 0.073f, 0.893f, 0.017f, 0.904f, 14, 0xc92au },   // Wind Over Stone
    { 0.4837f, 0.7714f, 0.192f, 0.780f, 0.232f, 0.718f, 0.921f, 0.910f, 14, 0xc9a9u },   // Vinyl Dust
    { 0.8105f, 0.6162f, 0.904f, 0.927f, 0.475f, 0.847f, 0.045f, 0.915f, 14, 0xc92au },   // Formant Noise
    { 0.7685f, 0.7526f, 0.780f, 0.904f, 0.435f, 0.977f, 0.401f, 0.921f, 14, 0xc92au },   // Violet Air
    { 0.9111f, 0.7609f, 0.944f, 0.989f, 0.898f, 1.000f, 0.209f, 0.927f, 14, 0xc96au },   // Grey Chamber
    { 0.8319f, 0.6495f, 0.847f, 0.944f, 0.977f, 0.904f, 0.260f, 0.932f, 14, 0xc96au },   // Digital Rain
    { 0.8622f, 0.7527f, 0.893f, 0.949f, 0.734f, 0.989f, 0.362f, 0.938f, 14, 0xd96au },   // Blue Sheen
    { 0.8218f, 0.8222f, 0.814f, 0.977f, 0.644f, 0.994f, 0.898f, 0.944f, 14, 0xc9aau },   // Noise Cathedral
    { 0.6004f, 0.4503f, 0.548f, 0.627f, 0.718f, 0.633f, 0.537f, 0.949f, 15, 0x8940u },   // Breathing Room
    { 0.6156f, 0.4136f, 0.356f, 0.746f, 0.910f, 0.503f, 0.627f, 0.955f, 15, 0x8948u },   // Fog Bank
    { 0.8121f, 0.4575f, 0.932f, 0.864f, 0.650f, 0.870f, 0.000f, 0.960f, 15, 0x892au },   // Throat Singer
    { 0.6711f, 0.3315f, 0.740f, 0.661f, 0.921f, 0.661f, 0.198f, 0.966f, 15, 0x8942u },   // Plucked Void
    { 0.6141f, 0.5748f, 0.520f, 0.701f, 0.548f, 0.723f, 0.599f, 0.972f, 15, 0x8928u },   // Wooden Knock
    { 0.6399f, 0.4491f, 0.678f, 0.684f, 0.525f, 0.701f, 0.277f, 0.977f, 15, 0x9920u },   // Bell Metal
    { 0.4553f, 0.5633f, 0.605f, 0.096f, 0.209f, 0.367f, 0.311f, 0.983f, 15, 0xc914u },   // Three Reeds
    { 0.6095f, 0.3745f, 0.588f, 0.571f, 0.723f, 0.605f, 0.458f, 0.989f, 15, 0x8940u },   // Drowned Echo
    { 0.1935f, 0.8073f, 0.040f, 0.124f, 0.040f, 0.621f, 0.972f, 0.994f, 15, 0x18985u },   // Evening Tide
    { 0.6521f, 0.4868f, 0.650f, 0.689f, 0.729f, 0.712f, 0.350f, 1.000f, 15, 0x8960u },   // Turning Sky
};
}

int builtinPresetMetaCount() { return static_cast<int>(sizeof(kMeta) / sizeof(kMeta[0])); }
const PresetMeta& builtinPresetMeta(int index) { static const PresetMeta none = { 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0, 0 }; return (index >= 0 && index < builtinPresetMetaCount()) ? kMeta[index] : none; }
int builtinPresetFamilyCount() { return static_cast<int>(sizeof(kFamilies) / sizeof(kFamilies[0])); }
const char* builtinPresetFamilyName(int family) { return (family >= 0 && family < builtinPresetFamilyCount()) ? kFamilies[family] : ""; }
const char* presetTagName(int bit) { return (bit >= 0 && bit < kNumPresetTags) ? kTagNames[bit] : ""; }

} // namespace ambient
