// Generated by Tools/preset_map.py -- do not edit. Measured from renders of every preset.
#include "ambient/PresetMeta.h"
#include "ambient/Presets.h"

namespace ambient {

namespace {
const char* const kFamilies[] = {
    "originals",
    "sleep / night",
    "cathedral / glass",
    "deep / sub / dark",
    "breath / flute / voice",
    "exotic scales",
    "shimmer / delay / motion",
    "cosmos / science fiction",
    "playable keys (brain off)",
    "long-form night arcs",
    "storm / cluster / texture",
    "sources (wavetable, FM, feedback)",
};
const char* const kTagNames[kNumPresetTags] = {
    "Dark", "Bright", "Calm", "Moving", "Tonal", "Noisy", "Wide", "Bass", "Dense", "Sparse", "Keys", "Generative", "Cosmos", "Feedback", "Sources", "JustIntonation", "Sub", "Stack", "Air"
};
const PresetMeta kMeta[] = {
    { 0.4022f, 0.7986f, 0.385f, 0.415f, 0.311f, 0.452f, 0.467f, 0.111f, 0, 0x8a00u },   // Init
    { 0.3295f, 0.7117f, 0.163f, 0.356f, 0.481f, 0.711f, 0.889f, 0.230f, 0, 0x18aa1u },   // Sleep Concert
    { 0.7689f, 0.6254f, 0.911f, 0.852f, 0.948f, 0.793f, 0.133f, 0.104f, 0, 0x8a6au },   // Glass Cathedral
    { 0.1118f, 0.9400f, 0.037f, 0.007f, 0.089f, 0.000f, 0.919f, 0.170f, 0, 0x8a95u },   // Subharmonic Deep
    { 0.7851f, 0.5893f, 0.830f, 0.933f, 0.919f, 0.896f, 0.111f, 0.096f, 0, 0x48a6au },   // Breath of Flutes
    { 0.1360f, 0.8637f, 0.052f, 0.156f, 0.044f, 0.111f, 0.963f, 0.156f, 0, 0x8a95u },   // Bohlen Night
    { 0.5011f, 0.7397f, 0.689f, 0.467f, 0.385f, 0.496f, 0.178f, 0.163f, 0, 0x8a00u },   // Otonal Shimmer
    { 0.2685f, 0.9400f, 0.741f, 0.207f, 0.081f, 0.007f, 0.311f, 0.178f, 0, 0xaa16u },   // Distant Storm
    { 0.5888f, 0.0735f, 0.770f, 0.681f, 0.444f, 0.807f, 0.148f, 0.000f, 0, 0x28622u },   // Dry Foreground Keys
    { 0.1766f, 0.8278f, 0.133f, 0.148f, 0.067f, 0.481f, 0.956f, 0.185f, 0, 0x18a85u },   // Sleep Concert II
    { 0.6506f, 0.5641f, 0.711f, 0.770f, 0.563f, 0.800f, 0.556f, 0.193f, 1, 0x8a2au },   // Midnight Pentatonic
    { 0.0948f, 0.9042f, 0.007f, 0.059f, 0.133f, 0.067f, 0.970f, 0.200f, 1, 0x18a95u },   // Deep Sleep Sub
    { 0.3618f, 0.7358f, 0.356f, 0.400f, 0.259f, 0.467f, 0.481f, 0.207f, 1, 0x8a00u },   // Dawn Drift
    { 0.7707f, 0.4820f, 0.881f, 0.926f, 0.593f, 0.933f, 0.415f, 0.215f, 1, 0x48a2au },   // Night Rain
    { 0.4388f, 0.8137f, 0.407f, 0.422f, 0.356f, 0.430f, 0.496f, 0.222f, 1, 0x8a00u },   // Slow Tide
    { 0.1514f, 0.9400f, 0.015f, 0.022f, 0.578f, 0.244f, 0.978f, 0.467f, 1, 0x18895u },   // Hypnos
    { 0.2833f, 0.9033f, 0.141f, 0.104f, 0.526f, 0.044f, 0.607f, 0.119f, 1, 0x8a15u },   // Warm Blanket
    { 0.7306f, 0.6357f, 0.941f, 0.378f, 0.793f, 0.704f, 0.007f, 0.126f, 1, 0x28a62u },   // Somnus Harmonics
    { 0.3068f, 0.8714f, 0.185f, 0.200f, 0.193f, 0.259f, 0.452f, 0.133f, 1, 0x8a15u },   // Breathing Dark
    { 0.2189f, 0.9400f, 0.096f, 0.096f, 0.119f, 0.074f, 0.904f, 0.141f, 1, 0x18a95u },   // Velvet Hours
    { 0.8670f, 0.5428f, 0.985f, 0.889f, 0.926f, 0.926f, 0.067f, 0.148f, 2, 0x8a6au },   // Ice Cathedral
    { 0.8313f, 0.5257f, 0.933f, 0.896f, 0.785f, 0.859f, 0.022f, 0.393f, 2, 0x4886au },   // Glass Choir
    { 0.6726f, 0.7073f, 0.815f, 0.630f, 0.644f, 0.600f, 0.081f, 0.400f, 2, 0x8802u },   // Crystal Bells
    { 0.5140f, 0.7772f, 0.296f, 0.533f, 0.852f, 0.304f, 0.674f, 0.407f, 2, 0x48851u },   // Wineglass Rim
    { 0.6487f, 0.7617f, 0.867f, 0.081f, 0.622f, 0.378f, 0.015f, 0.415f, 2, 0x28816u },   // High Organ
    { 0.3923f, 0.9071f, 0.363f, 0.052f, 0.652f, 0.022f, 0.059f, 0.422f, 2, 0x8814u },   // Stained Light
    { 0.3754f, 0.8278f, 0.193f, 0.252f, 0.363f, 0.407f, 0.570f, 0.430f, 2, 0x8805u },   // Frozen Chapel
    { 0.3932f, 0.7601f, 0.504f, 0.600f, 0.244f, 0.341f, 0.630f, 0.437f, 2, 0x8810u },   // Silver Threads
    { 0.6902f, 0.5630f, 0.844f, 0.800f, 0.570f, 0.830f, 0.363f, 0.444f, 2, 0x882au },   // Bright Pentatonic
    { 0.6300f, 0.5979f, 0.859f, 0.793f, 0.548f, 0.785f, 0.156f, 0.452f, 2, 0x882au },   // Prism
    { 0.1358f, 0.9036f, 0.044f, 0.089f, 0.007f, 0.089f, 0.881f, 0.459f, 3, 0x8895u },   // Abyss
    { 0.2098f, 0.8494f, 0.081f, 0.259f, 0.111f, 0.267f, 0.852f, 0.941f, 3, 0x8995u },   // Tectonic
    { 0.2419f, 0.7826f, 0.111f, 0.222f, 0.304f, 0.415f, 0.837f, 0.237f, 3, 0x48a85u },   // Whale Song
    { 0.7932f, 0.5146f, 0.896f, 0.948f, 0.889f, 0.948f, 0.711f, 0.244f, 3, 0x48aeau },   // Cave Water
    { 0.2587f, 0.8722f, 0.178f, 0.141f, 0.156f, 0.119f, 0.222f, 0.252f, 3, 0x8a15u },   // Undertow
    { 0.1752f, 0.9083f, 0.074f, 0.111f, 0.052f, 0.059f, 0.911f, 0.259f, 3, 0x8a95u },   // Bass Temple
    { 0.2465f, 0.8345f, 0.156f, 0.185f, 0.148f, 0.289f, 0.756f, 0.267f, 3, 0x8a95u },   // Slow Magma
    { 0.1753f, 0.8687f, 0.030f, 0.037f, 0.074f, 0.719f, 0.941f, 0.274f, 3, 0xaa5u },   // Deep Space Hum
    { 0.6844f, 0.5238f, 0.756f, 0.815f, 0.800f, 0.822f, 0.126f, 0.281f, 3, 0x48a6au },   // Subterranean Choir
    { 0.2767f, 0.7638f, 0.230f, 0.511f, 0.185f, 0.556f, 0.815f, 0.289f, 3, 0x8a81u },   // Low Pythagorean
    { 0.6301f, 0.5285f, 0.437f, 0.837f, 0.585f, 0.852f, 0.800f, 0.296f, 4, 0x48aa8u },   // Shakuhachi Air
    { 0.7614f, 0.5383f, 0.874f, 0.919f, 0.778f, 0.874f, 0.052f, 0.304f, 4, 0x4886au },   // Ocarina Clouds
    { 0.8197f, 0.4852f, 0.904f, 0.956f, 0.867f, 0.963f, 0.689f, 0.311f, 4, 0x4886au },   // Bamboo Wind
    { 0.7479f, 0.5755f, 0.852f, 0.785f, 0.963f, 0.763f, 0.030f, 0.319f, 4, 0x4986au },   // Alto Voices
    { 0.5737f, 0.7637f, 0.793f, 0.341f, 0.607f, 0.200f, 0.393f, 0.326f, 4, 0x9812u },   // Boys Choir
    { 0.5232f, 0.5593f, 0.696f, 0.748f, 0.178f, 0.837f, 0.844f, 0.333f, 4, 0x98a8u },   // Throat Drone
    { 0.8720f, 0.4292f, 0.963f, 0.970f, 0.970f, 1.000f, 0.719f, 0.341f, 4, 0x488eau },   // Whispered
    { 0.4151f, 0.6273f, 0.563f, 0.578f, 0.274f, 0.726f, 0.622f, 0.348f, 4, 0x8820u },   // Reed Organ
    { 0.7219f, 0.5391f, 0.807f, 0.904f, 0.956f, 0.889f, 0.259f, 0.356f, 4, 0x4886au },   // Wooden Flutes
    { 0.6910f, 0.6353f, 0.837f, 0.652f, 0.741f, 0.770f, 0.000f, 0.363f, 4, 0x48862u },   // Sirens Far Away
    { 0.5350f, 0.6308f, 0.719f, 0.622f, 0.489f, 0.644f, 0.289f, 0.370f, 5, 0x8802u },   // Slendro Dusk
    { 0.2739f, 0.8059f, 0.200f, 0.163f, 0.726f, 0.141f, 0.948f, 0.378f, 5, 0x88d5u },   // Bohlen Cathedral
    { 0.3038f, 0.8319f, 0.244f, 0.193f, 0.170f, 0.185f, 0.341f, 0.385f, 5, 0x8815u },   // Pythagorean Drone
    { 0.4891f, 0.8456f, 0.393f, 0.237f, 0.748f, 0.222f, 0.267f, 0.548f, 5, 0x8854u },   // Otonal Cloud
    { 0.4633f, 0.7278f, 0.556f, 0.526f, 0.459f, 0.533f, 0.726f, 0.541f, 5, 0x8880u },   // Subharmonic Bells
    { 0.5113f, 0.5971f, 0.704f, 0.585f, 0.378f, 0.756f, 0.422f, 0.533f, 5, 0x8822u },   // Harmonic Ladder
    { 0.3552f, 0.9360f, 0.215f, 0.044f, 0.696f, 0.015f, 0.074f, 0.526f, 5, 0x8815u },   // Seven Limit Garden
    { 0.4502f, 0.8532f, 0.496f, 0.304f, 0.252f, 0.319f, 0.207f, 0.519f, 5, 0x8810u },   // Minor Third Field
    { 0.5162f, 0.8167f, 0.474f, 0.333f, 0.719f, 0.296f, 0.489f, 0.511f, 5, 0x850u },   // Twelve Tone Fog
    { 0.5515f, 0.8346f, 0.822f, 0.281f, 0.504f, 0.126f, 0.215f, 0.504f, 5, 0x8816u },   // Pentatonic Rain
    { 0.4245f, 0.7359f, 0.400f, 0.407f, 0.326f, 0.422f, 0.430f, 0.496f, 6, 0x9800u },   // Shimmer Rise
    { 0.3541f, 0.8964f, 0.222f, 0.133f, 0.393f, 0.104f, 0.659f, 0.489f, 6, 0x9815u },   // Fifth Shimmer
    { 0.4648f, 0.6083f, 0.637f, 0.607f, 0.400f, 0.659f, 0.615f, 0.481f, 6, 0x9800u },   // Octave Below
    { 0.3806f, 0.8670f, 0.267f, 0.267f, 0.319f, 0.281f, 0.296f, 0.474f, 6, 0x8815u },   // Echo Canyon
    { 0.4000f, 0.4625f, 0.422f, 0.296f, 0.474f, 0.311f, 0.563f, 0.089f, 6, 0x8a14u },   // Ping Pong Drift
    { 0.3840f, 0.6612f, 0.519f, 0.704f, 0.126f, 0.459f, 0.252f, 0.556f, 6, 0x8808u },   // Rotating Sky
    { 0.5494f, 0.7950f, 0.333f, 0.541f, 1.000f, 0.170f, 0.541f, 0.578f, 6, 0x8850u },   // Slow Chorus Field
    { 0.2097f, 0.8890f, 0.148f, 0.119f, 0.037f, 0.096f, 0.830f, 0.585f, 6, 0x8895u },   // Tape Echo Drone
    { 0.5386f, 0.6703f, 0.644f, 0.474f, 0.496f, 0.593f, 0.304f, 0.563f, 6, 0x9800u },   // Shimmer Cathedral
    { 0.3660f, 0.6964f, 0.526f, 0.393f, 0.215f, 0.489f, 0.667f, 0.570f, 6, 0x9800u },   // Nineteenth Above
    { 0.5904f, 0.5971f, 0.378f, 0.822f, 0.556f, 0.637f, 0.644f, 0.637f, 7, 0x9808u },   // Nebula Drift
    { 0.4233f, 0.6660f, 0.370f, 0.563f, 0.281f, 0.548f, 0.504f, 0.644f, 7, 0x9800u },   // Frozen Nebula
    { 0.6173f, 0.6808f, 0.659f, 0.659f, 0.904f, 0.215f, 0.244f, 0.652f, 7, 0x9850u },   // Alien Choir
    { 0.5953f, 0.7137f, 0.548f, 0.570f, 0.837f, 0.400f, 0.378f, 0.659f, 7, 0x1840u },   // Forbidden Planet
    { 0.2439f, 0.9090f, 0.126f, 0.126f, 0.104f, 0.081f, 0.896f, 0.667f, 7, 0x9895u },   // Hull Resonance
    { 0.9228f, 0.4759f, 1.000f, 0.985f, 0.807f, 0.956f, 0.089f, 0.674f, 7, 0x4986au },   // Signal From Deep Space
    { 0.4593f, 0.6496f, 0.237f, 0.763f, 0.533f, 0.363f, 0.793f, 0.681f, 7, 0x9899u },   // Event Horizon
    { 0.7972f, 0.4526f, 0.889f, 0.941f, 0.681f, 0.993f, 0.637f, 0.689f, 7, 0x4982au },   // Ion Wind
    { 0.4814f, 0.5712f, 0.600f, 0.711f, 0.230f, 0.696f, 0.356f, 0.696f, 7, 0x9808u },   // Cryo Chamber
    { 0.6951f, 0.6747f, 0.726f, 0.696f, 0.859f, 0.504f, 0.193f, 0.704f, 7, 0x1942u },   // Pulsar Field
    { 0.6346f, 0.7184f, 0.481f, 0.489f, 0.815f, 0.474f, 0.200f, 0.593f, 7, 0x9840u },   // Ring World
    { 0.7161f, 0.4999f, 0.785f, 0.911f, 0.600f, 0.919f, 0.533f, 0.600f, 7, 0x4982au },   // Solar Wind
    { 0.3437f, 0.8523f, 0.207f, 0.178f, 0.296f, 0.133f, 0.348f, 0.607f, 7, 0x9815u },   // Derelict Ship
    { 0.6132f, 0.6414f, 0.615f, 0.726f, 0.763f, 0.326f, 0.333f, 0.615f, 7, 0x9858u },   // Telepathy
    { 0.2537f, 0.7262f, 0.281f, 0.667f, 0.030f, 0.607f, 0.807f, 0.622f, 7, 0x9881u },   // Warp Core
    { 0.5170f, 0.7035f, 0.319f, 0.689f, 0.541f, 0.348f, 0.444f, 0.630f, 7, 0x9810u },   // Comet Tail
    { 0.6516f, 0.6316f, 0.622f, 0.807f, 0.637f, 0.622f, 0.319f, 0.778f, 7, 0x9908u },   // Andromeda
    { 0.6101f, 0.5627f, 0.763f, 0.733f, 0.437f, 0.778f, 0.281f, 0.770f, 7, 0x992au },   // Ganymede Ice
    { 0.8975f, 0.5064f, 0.978f, 0.978f, 0.993f, 0.978f, 0.141f, 0.763f, 7, 0x4996au },   // Lost Transmission
    { 0.5745f, 0.6333f, 0.511f, 0.719f, 0.756f, 0.393f, 0.511f, 0.756f, 7, 0x9958u },   // Stellar Nursery
    { 0.5406f, 0.7419f, 0.541f, 0.615f, 0.674f, 0.178f, 0.400f, 0.748f, 7, 0x1910u },   // Xenomorph Hive
    { 0.5903f, 0.5284f, 0.289f, 0.859f, 0.659f, 0.733f, 0.733f, 0.741f, 7, 0x99a9u },   // Zero Gravity
    { 0.3582f, 0.7786f, 0.681f, 0.311f, 0.163f, 0.163f, 0.741f, 0.733f, 7, 0x9990u },   // Monolith
    { 0.6745f, 0.5993f, 0.748f, 0.756f, 0.874f, 0.689f, 0.163f, 0.726f, 7, 0x994au },   // Quasar
    { 0.2933f, 0.7278f, 0.067f, 0.741f, 0.333f, 0.541f, 0.926f, 0.719f, 7, 0x9989u },   // Dark Matter
    { 0.4556f, 0.6890f, 0.489f, 0.593f, 0.430f, 0.519f, 0.274f, 0.711f, 7, 0x9900u },   // Orbital Decay
    { 0.4727f, 0.7676f, 0.311f, 0.385f, 0.519f, 0.370f, 0.385f, 0.800f, 7, 0x9910u },   // First Contact
    { 0.6548f, 0.4976f, 0.607f, 0.830f, 0.422f, 0.881f, 0.600f, 0.807f, 7, 0x49928u },   // Plasma Sea
    { 0.8842f, 0.4669f, 0.926f, 0.963f, 0.978f, 0.985f, 0.548f, 0.785f, 7, 0x4996au },   // Void Whisper
    { 0.3253f, 0.7511f, 0.444f, 0.556f, 0.370f, 0.207f, 0.933f, 0.793f, 7, 0x9990u },   // Alien Cathedral
    { 0.3065f, 0.1037f, 0.252f, 0.452f, 0.222f, 0.630f, 0.785f, 0.022f, 8, 0x8681u },   // Warm Keys
    { 0.4112f, 0.0813f, 0.630f, 0.481f, 0.267f, 0.585f, 0.407f, 0.015f, 8, 0x8600u },   // Glass Keys
    { 0.4469f, 0.0984f, 0.459f, 0.519f, 0.911f, 0.252f, 0.770f, 0.052f, 8, 0x86d0u },   // Pad Keys
    { 0.7100f, 0.0600f, 0.674f, 0.867f, 0.933f, 0.867f, 0.096f, 0.044f, 8, 0x48668u },   // Flute Keys
    { 0.3738f, 0.0662f, 0.467f, 0.496f, 0.452f, 0.674f, 0.763f, 0.067f, 8, 0x8680u },   // Organ Keys
    { 0.5139f, 0.0806f, 0.452f, 0.778f, 0.615f, 0.652f, 0.696f, 0.074f, 8, 0x9608u },   // Cosmos Keys
    { 0.4176f, 0.1257f, 0.274f, 0.289f, 0.689f, 0.274f, 0.585f, 0.037f, 8, 0x9615u },   // Shimmer Keys
    { 0.1886f, 0.1199f, 0.089f, 0.244f, 0.015f, 0.615f, 0.859f, 0.030f, 8, 0x8685u },   // Sub Keys
    { 0.4835f, 0.1134f, 0.733f, 0.459f, 0.704f, 0.030f, 0.104f, 0.059f, 8, 0x9652u },   // Vowel Keys
    { 0.3555f, 0.1087f, 0.415f, 0.444f, 0.415f, 0.578f, 0.681f, 0.007f, 8, 0x9600u },   // Resonant Keys
    { 0.3087f, 0.7871f, 0.170f, 0.170f, 0.467f, 0.237f, 0.822f, 0.815f, 9, 0x18995u },   // All Night Arc
    { 0.6557f, 0.6710f, 0.667f, 0.674f, 0.844f, 0.748f, 0.326f, 0.822f, 9, 0x8960u },   // Tidal Hours
    { 0.3204f, 0.9171f, 0.119f, 0.067f, 0.896f, 0.052f, 0.704f, 0.830f, 9, 0x89d5u },   // Slow Sunrise
    { 0.4053f, 0.7013f, 0.348f, 0.504f, 0.289f, 0.526f, 0.474f, 0.837f, 9, 0x9900u },   // Ninety Minute Cycle
    { 0.4337f, 0.7744f, 0.430f, 0.437f, 0.407f, 0.444f, 0.519f, 0.844f, 9, 0x8900u },   // REM Drift
    { 0.4120f, 0.8429f, 0.326f, 0.326f, 0.237f, 0.230f, 0.237f, 0.852f, 9, 0x8910u },   // Dream Corridor
    { 0.4778f, 0.8069f, 0.652f, 0.348f, 0.341f, 0.385f, 0.185f, 0.859f, 9, 0x8910u },   // Deep Night Harmonics
    { 0.6108f, 0.7501f, 0.578f, 0.370f, 0.941f, 0.333f, 0.170f, 0.867f, 9, 0x8950u },   // Long Otonal Night
    { 0.4918f, 0.6729f, 0.341f, 0.644f, 0.511f, 0.511f, 0.593f, 0.874f, 9, 0x9900u },   // Sleeping Nebula
    { 0.3386f, 0.8130f, 0.259f, 0.319f, 0.200f, 0.356f, 0.578f, 0.881f, 9, 0x8911u },   // Morning Fade
    { 0.8590f, 0.4974f, 0.970f, 0.993f, 0.822f, 0.904f, 0.748f, 0.889f, 10, 0x29eau },   // Cluster Storm
    { 0.4221f, 0.8811f, 0.585f, 0.215f, 0.348f, 0.148f, 0.370f, 0.896f, 10, 0x914u },   // Micro Cluster
    { 0.5785f, 0.6727f, 0.533f, 0.548f, 0.770f, 0.570f, 0.526f, 0.904f, 10, 0x9940u },   // Rising Swarm
    { 0.3036f, 0.6818f, 0.104f, 0.363f, 0.141f, 0.815f, 0.867f, 0.911f, 10, 0x489a1u },   // Thunder Head
    { 0.5627f, 0.5568f, 0.304f, 0.844f, 0.711f, 0.681f, 0.778f, 0.919f, 10, 0x99c8u },   // Granular Sky
    { 0.9400f, 0.4403f, 0.993f, 1.000f, 0.985f, 0.941f, 0.437f, 0.926f, 10, 0xa96au },   // Inharmonic Field
    { 0.5565f, 0.7056f, 0.593f, 0.430f, 0.733f, 0.563f, 0.230f, 0.933f, 10, 0x940u },   // Dissonant Cathedral
    { 0.7349f, 0.4651f, 0.778f, 0.874f, 0.830f, 0.970f, 0.652f, 0.948f, 10, 0x4096au },   // White Storm
    { 0.5508f, 0.5946f, 0.919f, 0.274f, 0.096f, 0.437f, 0.044f, 0.956f, 11, 0xc906u },   // Vocal Morph Choir
    { 0.4954f, 0.6334f, 0.800f, 0.230f, 0.207f, 0.667f, 0.037f, 0.970f, 11, 0xc906u },   // Glass Table Drift
    { 0.2132f, 0.8099f, 0.570f, 0.074f, 0.059f, 0.193f, 0.874f, 0.963f, 11, 0xc994u },   // Organ Mixture Cloud
    { 0.8042f, 0.5546f, 0.948f, 0.881f, 0.881f, 0.844f, 0.459f, 0.978f, 11, 0xe96au },   // Metal Field
    { 0.7144f, 0.5966f, 0.956f, 0.637f, 0.630f, 0.741f, 0.119f, 0.985f, 11, 0xc922u },   // FM Bell Drone
    { 0.0600f, 0.9322f, 0.022f, 0.000f, 0.000f, 0.037f, 0.993f, 0.993f, 11, 0xc995u },   // Slow FM Tide
    { 0.0964f, 0.8647f, 0.000f, 0.015f, 0.667f, 0.911f, 1.000f, 1.000f, 11, 0xe9a5u },   // Feedback Hiss
    { 0.0954f, 0.1308f, 0.059f, 0.030f, 0.022f, 0.156f, 0.985f, 0.081f, 11, 0x2c695u },   // Three Voices, One Key
};
}

int numPresetMeta() { return static_cast<int>(sizeof(kMeta) / sizeof(kMeta[0])); }
const PresetMeta& presetMeta(int index) { static const PresetMeta none = { 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0, 0 }; return (index >= 0 && index < numPresetMeta()) ? kMeta[index] : none; }
int numPresetFamilies() { return static_cast<int>(sizeof(kFamilies) / sizeof(kFamilies[0])); }
const char* presetFamilyName(int family) { return (family >= 0 && family < numPresetFamilies()) ? kFamilies[family] : ""; }
const char* presetTagName(int bit) { return (bit >= 0 && bit < kNumPresetTags) ? kTagNames[bit] : ""; }

} // namespace ambient
