// Generated by Tools/make_content_pack.py -- do not edit.
// Content package v2: 5 archives, 8.34 GB.
procedure AddContentDownloads(Page: TDownloadWizardPage);
begin
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v2-part1.zip', 'AmbientSynth-content-v2-part1.zip', 'da7139bd7b8db8ffb6be484aec9876ef820f055eb9bd17e29bbf1bb7616c758c');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v2-part2.zip', 'AmbientSynth-content-v2-part2.zip', 'e86ff8b55c047e15034df94ccdddaf512869ff0aedb27d8847c00a7f7fca62c8');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v2-part3.zip', 'AmbientSynth-content-v2-part3.zip', '19533f72d2dde2dc3b0b97011dc3349846e06252c588beb01e1cad02bc79dac1');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v2-part4.zip', 'AmbientSynth-content-v2-part4.zip', '60c10be83038a4566bef405e123990acc9988c7079dc927ea89f40e672f3067c');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v2-part5.zip', 'AmbientSynth-content-v2-part5.zip', '3c2af643c3dc72a80266dca02f6987c9f57753e273b9bae6064cebd447d93e5d');
end;
