// Generated by Tools/make_content_pack.py -- do not edit.
// Content package v4: 8 archives, 10.55 GB.
procedure AddContentDownloads(Page: TDownloadWizardPage);
begin
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v4-part1.zip', 'AmbientSynth-content-v4-part1.zip', '494e6cbd207324033e2a4ea9ab68d2ff04e9b04c9d8d6ede81aa887ceb38671b');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v4-part2.zip', 'AmbientSynth-content-v4-part2.zip', 'ef3278af72ca7e4919ff7ac24223c444f6e84c338d32003e94dbe8cc9e0f83e4');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v4-part3.zip', 'AmbientSynth-content-v4-part3.zip', 'a68d8be2a61e41cef77df566b94637ef9fa4ee1e5022e61119a849d9198458a7');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v4-part4.zip', 'AmbientSynth-content-v4-part4.zip', '5dfc4f9e110270a76bb8f6ba4174a74f934da9cc1250ad97f306771d471b4e6c');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v4-part5.zip', 'AmbientSynth-content-v4-part5.zip', '56ffc5dafd5d5a59d4b3c51370a27a8904a33471d4d8932c2d6e004e65a05602');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v4-part6.zip', 'AmbientSynth-content-v4-part6.zip', '5453f5bc4338a0199019c5647d0b08127a4996d1146caf96661c91cd726f9ad9');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v4-part7.zip', 'AmbientSynth-content-v4-part7.zip', 'e4e340c4a4de855cdf7860493d67d5e4442bde7301a12868af370e9cf7bc18be');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v4-part8.zip', 'AmbientSynth-content-v4-part8.zip', '42f19ed06c547a8d291e41d2c4384b2338b8d727759dcdcaff9c3944df68cb7b');
end;
