; Generated by Tools/make_content_pack.py -- do not edit.
; Content package v2: 5 archives, 8.34 GB.
Source: "{tmp}\AmbientSynth-content-v2-part1.zip"; DestDir: "{code:LibDir}"; Check: ContentDownloaded; \
    Flags: external extractarchive recursesubdirs ignoreversion
Source: "{tmp}\AmbientSynth-content-v2-part2.zip"; DestDir: "{code:LibDir}"; Check: ContentDownloaded; \
    Flags: external extractarchive recursesubdirs ignoreversion
Source: "{tmp}\AmbientSynth-content-v2-part3.zip"; DestDir: "{code:LibDir}"; Check: ContentDownloaded; \
    Flags: external extractarchive recursesubdirs ignoreversion
Source: "{tmp}\AmbientSynth-content-v2-part4.zip"; DestDir: "{code:LibDir}"; Check: ContentDownloaded; \
    Flags: external extractarchive recursesubdirs ignoreversion
Source: "{tmp}\AmbientSynth-content-v2-part5.zip"; DestDir: "{code:LibDir}"; Check: ContentDownloaded; \
    Flags: external extractarchive recursesubdirs ignoreversion
