; Generated by Tools/make_content_pack.py -- do not edit.
; Content package v1: 3 archives, 3.06 GB.
Source: "{tmp}\AmbientSynth-content-v1-part1.zip"; DestDir: "{code:LibDir}"; Check: ContentDownloaded; \
    Flags: external extractarchive recursesubdirs ignoreversion
Source: "{tmp}\AmbientSynth-content-v1-part2.zip"; DestDir: "{code:LibDir}"; Check: ContentDownloaded; \
    Flags: external extractarchive recursesubdirs ignoreversion
Source: "{tmp}\AmbientSynth-content-v1-part3.zip"; DestDir: "{code:LibDir}"; Check: ContentDownloaded; \
    Flags: external extractarchive recursesubdirs ignoreversion
