// Generated by Tools/make_content_pack.py -- do not edit.
// Content package v1: 5 archives, 4.90 GB.
procedure AddContentDownloads(Page: TDownloadWizardPage);
begin
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v1-part1.zip', 'AmbientSynth-content-v1-part1.zip', '356c3850e8206339ababc1b732371d930b275dd945999e180b80a808e52326f4');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v1-part2.zip', 'AmbientSynth-content-v1-part2.zip', '9cfdc9d47e2c8ed21ff5a5ff1f1c71a60e93a54838b58ff7fc590acc71f86a4e');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v1-part3.zip', 'AmbientSynth-content-v1-part3.zip', '4c0e8af7e3335f2ffe019dde54212ee37f19f7eeae31d3e57332a2c4d5670499');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v1-part4.zip', 'AmbientSynth-content-v1-part4.zip', 'dbdf0190a201b74bd2ba8a9a24b3b7f539f9967ab9946110f404cc930e459afb');
  Page.Add('{#ContentBaseUrl}/AmbientSynth-content-v1-part5.zip', 'AmbientSynth-content-v1-part5.zip', '7684490b6a0c733d0156d49f613653b79a73a3e7feb5e2fc665c11248885f4ec');
end;
